-- Find total customers by countries
SELECT country, COUNT(DISTINCT customer_id) AS total_customers FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT gender, COUNT(DISTINCT customer_id) AS total_customers FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT category, COUNT(DISTINCT product_id) AS total_products FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average price in each category?
SELECT category, AVG(cost) AS avg_price FROM gold.dim_products
GROUP BY category
ORDER BY avg_price DESC;

-- What is the total revenue generated for each category?
SELECT p.category, SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT c.customer_id, c.first_name, c.last_name, SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT c.country, SUM(f.quantity) total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;